version: 2.1

orbs:
  maven: circleci/maven@0.0.12

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
  maven_verify:
    jobs:
      - maven/verify # checkout, build, test, and upload test results